---
all:
  children:
    web:
      hosts:
        prod-web-01:
          ansible_host: 10.0.2.10
          ansible_user: ubuntu
        prod-web-02:
          ansible_host: 10.0.2.11
          ansible_user: ubuntu
